/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.NurseRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.NurseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreya Vivek Bhosale
 */
public class PatientNurseRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private NurseOrganization nurseOrganization;
    private WorkRequest req;
    private Enterprise enter;
    private static final Pattern bloodPattern = Pattern.compile("^(A|B|AB|O)[-+]$");

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public PatientNurseRequestJPanel(JPanel userProcessContainer, UserAccount account, NurseOrganization organization, EcoSystem business, Enterprise enter, WorkRequest req) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.nurseOrganization = (NurseOrganization) organization;
        this.enter = enter;
        this.req = req;
        populateData();
    }

    private int validateBloodGroup(String validate) {
        Matcher match = bloodPattern.matcher(validate);
        if (match.matches()) {
            return 1;
        }
        return 0;
    }

    private void populateData() {

        txtFirstName.setText(req.getPatientFirstname());
        txtLastName.setText(req.getPatientLastname());
        txtAge.setText(Integer.toString(req.getPage()));
        txtheight.setText(Integer.toString(req.getPheight()));
        txtweight.setText(Integer.toString(req.getPweight()));
        txtgender.setText(req.getPgender());
        String picture = req.getPimage();
        System.out.println(picture);
        ImageIcon pic1 = new ImageIcon(picture);
        pic1 = new ImageIcon(pic1.getImage().getScaledInstance(130, 150, Image.SCALE_SMOOTH));
        labelImage.setIcon(pic1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtBloodGroup = new rojerusan.RSMetroTextPlaceHolder();
        txtgender = new rojerusan.RSMetroTextPlaceHolder();
        txtweight = new rojerusan.RSMetroTextPlaceHolder();
        txtheight = new rojerusan.RSMetroTextPlaceHolder();
        txtAge = new rojerusan.RSMetroTextPlaceHolder();
        txtLastName = new rojerusan.RSMetroTextPlaceHolder();
        txtFirstName = new rojerusan.RSMetroTextPlaceHolder();
        jLabel23 = new javax.swing.JLabel();
        txtdiagnosis = new rojerusan.RSMetroTextPlaceHolder();
        jLabel24 = new javax.swing.JLabel();
        txtBodytemp = new rojerusan.RSMetroTextPlaceHolder();
        txtGlucose = new rojerusan.RSMetroTextPlaceHolder();
        txtBloodPressure = new rojerusan.RSMetroTextPlaceHolder();
        jScrollPanel = new javax.swing.JScrollPane();
        txtSymptoms = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtpatientfee = new rojerusan.RSMetroTextPlaceHolder();
        jLabel30 = new javax.swing.JLabel();
        txtpriority = new rojerusan.RSMetroTextPlaceHolder();
        bttnBack = new rojerusan.RSMaterialButtonRectangle();
        bttnBack1 = new rojerusan.RSMaterialButtonRectangle();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Priority");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("PATIENT PHOTO");

        jPanel2.setBackground(new java.awt.Color(235, 122, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("PATIENT REQUEST");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Weight");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Height");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Age");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Last Name");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("First Name");

        txtBloodGroup.setForeground(new java.awt.Color(15, 19, 52));
        txtBloodGroup.setToolTipText("");
        txtBloodGroup.setBorderColor(new java.awt.Color(51, 51, 51));
        txtBloodGroup.setBotonColor(new java.awt.Color(235, 122, 102));
        txtBloodGroup.setPhColor(new java.awt.Color(235, 122, 102));
        txtBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodGroupActionPerformed(evt);
            }
        });

        txtgender.setForeground(new java.awt.Color(15, 19, 52));
        txtgender.setToolTipText("");
        txtgender.setBorderColor(new java.awt.Color(51, 51, 51));
        txtgender.setBotonColor(new java.awt.Color(235, 122, 102));
        txtgender.setPhColor(new java.awt.Color(235, 122, 102));
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        txtweight.setForeground(new java.awt.Color(15, 19, 52));
        txtweight.setToolTipText("");
        txtweight.setBorderColor(new java.awt.Color(51, 51, 51));
        txtweight.setBotonColor(new java.awt.Color(235, 122, 102));
        txtweight.setPhColor(new java.awt.Color(235, 122, 102));
        txtweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtweightActionPerformed(evt);
            }
        });

        txtheight.setForeground(new java.awt.Color(15, 19, 52));
        txtheight.setToolTipText("");
        txtheight.setBorderColor(new java.awt.Color(51, 51, 51));
        txtheight.setBotonColor(new java.awt.Color(235, 122, 102));
        txtheight.setPhColor(new java.awt.Color(235, 122, 102));
        txtheight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheightActionPerformed(evt);
            }
        });

        txtAge.setForeground(new java.awt.Color(15, 19, 52));
        txtAge.setToolTipText("");
        txtAge.setBorderColor(new java.awt.Color(51, 51, 51));
        txtAge.setBotonColor(new java.awt.Color(235, 122, 102));
        txtAge.setPhColor(new java.awt.Color(235, 122, 102));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtLastName.setForeground(new java.awt.Color(15, 19, 52));
        txtLastName.setToolTipText("");
        txtLastName.setBorderColor(new java.awt.Color(51, 51, 51));
        txtLastName.setBotonColor(new java.awt.Color(235, 122, 102));
        txtLastName.setPhColor(new java.awt.Color(235, 122, 102));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        txtFirstName.setForeground(new java.awt.Color(15, 19, 52));
        txtFirstName.setToolTipText("");
        txtFirstName.setBorderColor(new java.awt.Color(51, 51, 51));
        txtFirstName.setBotonColor(new java.awt.Color(235, 122, 102));
        txtFirstName.setPhColor(new java.awt.Color(235, 122, 102));
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Blood Group");

        txtdiagnosis.setForeground(new java.awt.Color(15, 19, 52));
        txtdiagnosis.setToolTipText("");
        txtdiagnosis.setBorderColor(new java.awt.Color(51, 51, 51));
        txtdiagnosis.setBotonColor(new java.awt.Color(235, 122, 102));
        txtdiagnosis.setPhColor(new java.awt.Color(235, 122, 102));
        txtdiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiagnosisActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Gender");

        txtBodytemp.setForeground(new java.awt.Color(15, 19, 52));
        txtBodytemp.setToolTipText("");
        txtBodytemp.setBorderColor(new java.awt.Color(51, 51, 51));
        txtBodytemp.setBotonColor(new java.awt.Color(235, 122, 102));
        txtBodytemp.setPhColor(new java.awt.Color(235, 122, 102));
        txtBodytemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodytempActionPerformed(evt);
            }
        });

        txtGlucose.setForeground(new java.awt.Color(15, 19, 52));
        txtGlucose.setToolTipText("");
        txtGlucose.setBorderColor(new java.awt.Color(51, 51, 51));
        txtGlucose.setBotonColor(new java.awt.Color(235, 122, 102));
        txtGlucose.setPhColor(new java.awt.Color(235, 122, 102));
        txtGlucose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGlucoseActionPerformed(evt);
            }
        });

        txtBloodPressure.setForeground(new java.awt.Color(15, 19, 52));
        txtBloodPressure.setToolTipText("");
        txtBloodPressure.setBorderColor(new java.awt.Color(51, 51, 51));
        txtBloodPressure.setBotonColor(new java.awt.Color(235, 122, 102));
        txtBloodPressure.setPhColor(new java.awt.Color(235, 122, 102));
        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });

        txtSymptoms.setColumns(20);
        txtSymptoms.setRows(5);
        txtSymptoms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jScrollPanel.setViewportView(txtSymptoms);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Possible Diagnosis");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Symptoms");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Body Temperature");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Glucose Level");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Blood Pressure");

        txtpatientfee.setForeground(new java.awt.Color(15, 19, 52));
        txtpatientfee.setToolTipText("");
        txtpatientfee.setBorderColor(new java.awt.Color(51, 51, 51));
        txtpatientfee.setBotonColor(new java.awt.Color(235, 122, 102));
        txtpatientfee.setPhColor(new java.awt.Color(235, 122, 102));
        txtpatientfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientfeeActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Diagnosis Fee");

        txtpriority.setForeground(new java.awt.Color(15, 19, 52));
        txtpriority.setToolTipText("");
        txtpriority.setBorderColor(new java.awt.Color(51, 51, 51));
        txtpriority.setBotonColor(new java.awt.Color(235, 122, 102));
        txtpriority.setPhColor(new java.awt.Color(235, 122, 102));
        txtpriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriorityActionPerformed(evt);
            }
        });

        bttnBack.setBackground(new java.awt.Color(235, 122, 102));
        bttnBack.setForeground(new java.awt.Color(51, 51, 51));
        bttnBack.setText("Back");
        bttnBack.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBackActionPerformed(evt);
            }
        });

        bttnBack1.setBackground(new java.awt.Color(235, 122, 102));
        bttnBack1.setForeground(new java.awt.Color(51, 51, 51));
        bttnBack1.setText("SUBMIT RESULT");
        bttnBack1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bttnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGlucose, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpriority, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpatientfee, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGlucose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtBodytemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpatientfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodGroupActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweightActionPerformed

    private void txtheightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheightActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtdiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiagnosisActionPerformed

    private void txtBodytempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodytempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodytempActionPerformed

    private void txtGlucoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGlucoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGlucoseActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void txtpatientfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientfeeActionPerformed

    private void txtpriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriorityActionPerformed

    private void bttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBackActionPerformed
        userProcessContainer.remove(this);
        req.setStatus("Nurse Waiting");
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HealthCampWorkRequestJPanel dwjp = (HealthCampWorkRequestJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bttnBackActionPerformed

    private void bttnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBack1ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        int checkBlood = 0;

        if (txtBloodGroup.getText().isEmpty() || txtBloodPressure.getText().isEmpty() || txtBodytemp.getText().isEmpty() || txtGlucose.getText().isEmpty() || txtSymptoms.getText().isEmpty() || txtdiagnosis.getText().isEmpty() || txtpriority.getText().isEmpty() || txtpatientfee.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Patient Registration cannot be completed as one or more fields are empty");
            return;
        } else {
            int checkint = 0;
            check = 1;

            checkBlood = validateBloodGroup(txtBloodGroup.getText());
            String fname = txtFirstName.getText();
            String lname = txtLastName.getText();
            int age1 = 0;
            int height1 = 0;
            int weight1 = 0;
            float bTemp = 0;
            float gLevel = 0;
            float bPress = 0;
            int patientFee = 0;

            try {
                age1 = Integer.parseInt(txtAge.getText());
                height1 = Integer.parseInt(txtheight.getText());
                weight1 = Integer.parseInt(txtweight.getText());
                bTemp = Float.parseFloat(txtBodytemp.getText());
                gLevel = Float.parseFloat(txtGlucose.getText());
                bPress = Float.parseFloat(txtBloodPressure.getText());
                patientFee = Integer.parseInt(txtpatientfee.getText());
                checkint = 1;
                if (checkBlood != 1) {
                    JOptionPane.showMessageDialog(null, "Please Enter the Blood Group in the format - 'B+'");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Please Enter the Body Temperature, Blood Pressure, Glucose Level and Patient Fee in Digits!");
            }
            System.out.println("Entering if????????????????????????????");
            if (check == 1 && checkint == 1 && checkBlood != 0) {
                System.out.println("Nurse resuest::" + req.getTypeOfRequest());
                if ((req.getTypeOfRequest().equals("PatientTest"))) {
                    req.setPatientId();
                    req.setPatientFirstname(txtFirstName.getText());
                    req.setPatientLastname(txtLastName.getText());
                    req.setPage(Integer.parseInt(txtAge.getText()));
                    req.setPheight(Integer.parseInt(txtheight.getText()));
                    req.setPweight(Integer.parseInt(txtweight.getText()));
                    req.setPgender(txtgender.getText());
                    req.setPbloodgrp(txtBloodGroup.getText());
                    req.setPbloodpres(txtBloodPressure.getText());
                    req.setPbodytemp(Float.parseFloat(txtBodytemp.getText()));
                    req.setPgulcoselvl(Float.parseFloat(txtGlucose.getText()));
                    req.setPsymptoms(txtSymptoms.getText());
                    req.setPdiagnosis(txtdiagnosis.getText());
                    req.setPpriority(txtpriority.getText());
                    req.setReceiver(userAccount);
                    req.setApproxPatientFee(Integer.parseInt(txtpatientfee.getText()));
                    System.out.println("to check is set:" + req.getPatientFirstname());
                    userProcessContainer.remove(this);
                    req.setStatus("Admin Waiting");
                    req.setTypeOfRequest("NGODecision");
                    JOptionPane.showMessageDialog(null, "Patient Details sent to the System Admin for Approval!");
                    Component[] componentArray = userProcessContainer.getComponents();
                    Component component = componentArray[componentArray.length - 1];
                    HealthCampWorkRequestJPanel dwjp = (HealthCampWorkRequestJPanel) component;
                    dwjp.populateTable();
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.previous(userProcessContainer);
                    for (UserAccount sys : business.getUserAccountDirectory().getUserAccountList()) {
                        System.out.println(sys);
                        req.setReceiver(sys);
                        sys.getWorkQueue().getWorkRequestList().add(req);

                        txtFirstName.setText("");
                        txtLastName.setText("");
                        txtAge.setText("");
                        txtheight.setText("");
                        txtweight.setText("");
                        txtgender.setText("");
                        txtBloodGroup.setText("");
                        txtBloodPressure.setText("");
                        txtBodytemp.setText("");
                        txtGlucose.setText("");
                        txtSymptoms.setText("");
                        txtpatientfee.setText("");
                        txtdiagnosis.setText("");
                        txtpriority.setText("");
                    }
                    //userAccount.getWorkQueue().getWorkRequestList().add(req);
                }
            }
        }
    }//GEN-LAST:event_bttnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle bttnBack;
    private rojerusan.RSMaterialButtonRectangle bttnBack1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JLabel labelImage;
    private rojerusan.RSMetroTextPlaceHolder txtAge;
    private rojerusan.RSMetroTextPlaceHolder txtBloodGroup;
    private rojerusan.RSMetroTextPlaceHolder txtBloodPressure;
    private rojerusan.RSMetroTextPlaceHolder txtBodytemp;
    private rojerusan.RSMetroTextPlaceHolder txtFirstName;
    private rojerusan.RSMetroTextPlaceHolder txtGlucose;
    private rojerusan.RSMetroTextPlaceHolder txtLastName;
    private javax.swing.JTextArea txtSymptoms;
    private rojerusan.RSMetroTextPlaceHolder txtdiagnosis;
    private rojerusan.RSMetroTextPlaceHolder txtgender;
    private rojerusan.RSMetroTextPlaceHolder txtheight;
    private rojerusan.RSMetroTextPlaceHolder txtpatientfee;
    private rojerusan.RSMetroTextPlaceHolder txtpriority;
    private rojerusan.RSMetroTextPlaceHolder txtweight;
    // End of variables declaration//GEN-END:variables
}
