/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FundCharityEnterprise;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import java.util.logging.*;

/**
 *
 * @author Shreya Vivek Bhosale
 */
public class SendHospitalRequest extends javax.swing.JPanel {

    /**
     * Creates new form SendHospitalRequest
     */
    private JPanel userProcessContainer;
    private EcoSystem eco;
    private static int funds = 0;
    int count = 0;
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);

    public SendHospitalRequest(JPanel container, EcoSystem eco) {
        initComponents();
        this.userProcessContainer = container;
        this.eco = eco;
        initComponents();
        populateTable();
        populateJComboBox();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        System.out.println("Welcome!");
        for (Network net : eco.getNetworkList()) {
            for (Enterprise enter : net.getEnterpriseDirectory().getEnterpriseList()) {
                if (enter.getEnterpriseType().equals(Enterprise.EnterpriseType.Event)) {
                    System.out.println(enter.getEnterpriseType());
                    for (UserAccount user : enter.getUserAccountDirectory().getUserAccountList()) {
                        System.out.println("+++++++++++++++++=" + user.getRole().toString());
                        System.out.println("++++++*******" + user.getUsername());

                        if (user.getUsername().equals("mafund")) {
                            count++;
                            for (WorkRequest req : user.getWorkQueue().getWorkRequestList()) {
                                System.out.println("Request:" + req);
                                System.out.println("Request Type:" + req.getTypeOfRequest());
                                if (req.getTypeOfRequest().equals("Hospital Patient") || (req.getTypeOfRequest().equals("Fund Patient"))) {
                                    Object[] row = new Object[8];
                                    row[0] = req.getPatientFirstname();
                                    row[1] = req.getPatientLastname();
                                    row[2] = req.getPpriority();
                                    row[3] = req.getPage();
                                    row[4] = req;
                                    row[5] = req.getStatus();
                                    row[6] = req.getPdiagnosis();
                                    row[7] = req.getApproxPatientFee();
                                    model.addRow(row);
                                }
                            }
                        }
                    }
                    if (count == 1) {
                        FundCharityEnterprise event = (FundCharityEnterprise) enter;
                        int temp = event.getFundsCollected();
                        System.out.println(temp);
                        if (temp != funds) {
                            funds = temp;
                        }
                        System.out.println(funds);
                        fundcollected.setText(Integer.toString(funds));
                    }
                }
            }
        }
    }

    public void populateJComboBox() {
        comboHospital.removeAllItems();
        for (Network network : eco.getNetworkList()) {
            for (Enterprise enter : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enter.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)) {
                    System.out.print(enter.getName());
                    comboHospital.addItem(enter);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fundcollected = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        bttnBack = new rojerusan.RSMaterialButtonRectangle();
        bttnAssignToHospital = new rojerusan.RSMaterialButtonRectangle();
        comboHospital = new rojerusan.RSComboMetro();

        setBackground(new java.awt.Color(232, 243, 255));

        jPanel1.setBackground(new java.awt.Color(15, 19, 52));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("HOSPITAL REQUEST MANAGEMENT");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FUNDS COLLECTED:");

        fundcollected.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fundcollected.setForeground(new java.awt.Color(255, 255, 255));
        fundcollected.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(745, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fundcollected)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fundcollected))
                .addContainerGap())
        );

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Patient ", "Priority", "Age", "Request Type", "Status", "Disease", "Hospital Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setSelectionBackground(new java.awt.Color(15, 19, 52));
        jScrollPane1.setViewportView(workRequestJTable);

        bttnBack.setBackground(new java.awt.Color(15, 19, 52));
        bttnBack.setText("Back");
        bttnBack.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBackActionPerformed(evt);
            }
        });

        bttnAssignToHospital.setBackground(new java.awt.Color(15, 19, 52));
        bttnAssignToHospital.setText("ASSIGN TO HOSPITAL");
        bttnAssignToHospital.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bttnAssignToHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAssignToHospitalActionPerformed(evt);
            }
        });

        comboHospital.setBackground(new java.awt.Color(15, 19, 52));
        comboHospital.setColorArrow(new java.awt.Color(15, 19, 52));
        comboHospital.setColorBorde(new java.awt.Color(15, 19, 52));
        comboHospital.setColorFondo(new java.awt.Color(15, 19, 52));
        comboHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(641, 641, 641)
                        .addComponent(comboHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bttnAssignToHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnAssignToHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bttnBackActionPerformed

    private void bttnAssignToHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAssignToHospitalActionPerformed
        Enterprise enter = (Enterprise) comboHospital.getSelectedItem();
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please make a selection");
            return;
        }
        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 4);
        if ((funds - request.getApproxPatientFee()) >= 0) {
            System.out.println(request.getStatus());
            if (request.getStatus().equals("Hospital Sent")) {
                JOptionPane.showMessageDialog(null, "Patient Already Added");
            } else if (request.getStatus().equals("Funding Process is going on")) {
                for (UserAccount user : enter.getUserAccountDirectory().getUserAccountList()) {
                    if (user.getUsername().equals("mahospital")) {
                        // System.out.println(user);
                        //System.out.println(request.getStatus());
                        //System.out.println(user.getWorkQueue().getWorkRequestList());
                        request.setStatus("Hospital Sent");
                        request.setTypeOfRequest("Hospital Patient");
                        user.getWorkQueue().getWorkRequestList().add(request);
                        //System.out.println(request.getStatus());
                        JOptionPane.showMessageDialog(null, "Details Sent to Hospital! ");
                        populateTable();
                    }
                }
                for (Organization organ : enter.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount user : organ.getUserAccountDirectory().getUserAccountList()) {
                        if (user.getRole().toString().equals("ReceptionistRole")) {
                            System.out.println(user.getWorkQueue().getWorkRequestList());
                            System.out.println(request.getStatus());
                            user.getWorkQueue().getWorkRequestList().add(request);
                            System.out.println(request.getStatus());
                            JOptionPane.showMessageDialog(null, "Patient Successfully Added To Receptionist");
                            populateTable();
                            logr.info("Patient has been assigned to hospital, check with receptionist");
                        }
                    }
                }
            } else if (request.getStatus().equals("Treatment Completed")) {
                JOptionPane.showMessageDialog(null, "Treatment is already completed");
            } else if (request.getStatus().equals("Assigned To Doctor")) {
                JOptionPane.showMessageDialog(null, "Patient has been assigned to Doctor already");
            } else if (request.getStatus().equals("Pending")) {
                JOptionPane.showMessageDialog(null, "Pending from doctor");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient Funds");
        }
    }//GEN-LAST:event_bttnAssignToHospitalActionPerformed

    private void comboHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle bttnAssignToHospital;
    private rojerusan.RSMaterialButtonRectangle bttnBack;
    private rojerusan.RSComboMetro comboHospital;
    private javax.swing.JLabel fundcollected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
