/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdministrativeCampRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ashishroy
 */
public class ViewCampRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private WorkRequest request;
    private Enterprise enterprise;
    private Network network;

    /**
     * Creates new form ViewCampRequestJPanel
     */
    public ViewCampRequestJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, WorkRequest request, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.request = request;
        this.enterprise = enterprise;
        this.network = network;
        //System.out.println(business.getNetworkList());
        txtCampID.setText(Integer.toString(request.getCampId()));
        txtCity.setText(request.getCity());
        txtName.setText(request.getVolunteerName());
        txtNumberPeopleAffected.setText(request.getPeopleAffected());
        txtAffectedChildren.setText(request.getPercentChild());
        txtAffectedChildren.setText(request.getPercentElder());
        txtState.setText(request.getState());
        txtStreetAddress.setText(request.getStreet());
        txtZipCode.setText(request.getZipcode());
        if (request.getEventDate() != null) {
            //      SimpleDateFormat format = new SimpleDateFormat("MM-dd-yyyy");
            //      String dateConvert = format.format(request.getEventDate());
            healthcampDate.setDate(request.getEventDate());
        }
        populateEnterpriseComboBox(Enterprise.EnterpriseType.Hospital, network);

        if (request.getStatus().equals("Completed")) {
            bttnApprove.setEnabled(false);
        }

    }

    private void populateEnterpriseComboBox(Enterprise.EnterpriseType type, Network network) {
        cmboEnterprise.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (type.getValue().equals(enterprise.getEnterpriseType().getValue())) {
                cmboEnterprise.addItem(enterprise);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmboEnterprise = new rojerusan.RSComboMetro();
        bttnBack = new rojerusan.RSMaterialButtonRectangle();
        bttnApprove = new rojerusan.RSMaterialButtonRectangle();
        txtCampID = new rojerusan.RSMetroTextPlaceHolder();
        txtName = new rojerusan.RSMetroTextPlaceHolder();
        txtStreetAddress = new rojerusan.RSMetroTextPlaceHolder();
        txtCity = new rojerusan.RSMetroTextPlaceHolder();
        txtState = new rojerusan.RSMetroTextPlaceHolder();
        txtZipCode = new rojerusan.RSMetroTextPlaceHolder();
        txtNumberPeopleAffected = new rojerusan.RSMetroTextPlaceHolder();
        txtAffectedChildren = new rojerusan.RSMetroTextPlaceHolder();
        txtAddectedElders = new rojerusan.RSMetroTextPlaceHolder();
        healthcampDate = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("State");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("ZipCode");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("No. of People in Camp");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("No. of Children");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("No. of Elders");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Camp ID");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Health Camp Event Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Enterprise");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Street Address");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("City");

        cmboEnterprise.setBackground(new java.awt.Color(235, 122, 102));
        cmboEnterprise.setForeground(new java.awt.Color(51, 51, 51));
        cmboEnterprise.setColorArrow(new java.awt.Color(235, 122, 102));
        cmboEnterprise.setColorBorde(new java.awt.Color(51, 51, 51));
        cmboEnterprise.setColorFondo(new java.awt.Color(235, 122, 102));

        bttnBack.setBackground(new java.awt.Color(235, 122, 102));
        bttnBack.setForeground(new java.awt.Color(51, 51, 51));
        bttnBack.setText("Back");
        bttnBack.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBackActionPerformed(evt);
            }
        });

        bttnApprove.setBackground(new java.awt.Color(235, 122, 102));
        bttnApprove.setForeground(new java.awt.Color(51, 51, 51));
        bttnApprove.setText("APPROVE");
        bttnApprove.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bttnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnApproveActionPerformed(evt);
            }
        });

        txtCampID.setForeground(new java.awt.Color(15, 19, 52));
        txtCampID.setToolTipText("");
        txtCampID.setBorderColor(new java.awt.Color(51, 51, 51));
        txtCampID.setBotonColor(new java.awt.Color(235, 122, 102));
        txtCampID.setPhColor(new java.awt.Color(235, 122, 102));
        txtCampID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampIDActionPerformed(evt);
            }
        });

        txtName.setForeground(new java.awt.Color(15, 19, 52));
        txtName.setToolTipText("");
        txtName.setBorderColor(new java.awt.Color(51, 51, 51));
        txtName.setBotonColor(new java.awt.Color(235, 122, 102));
        txtName.setPhColor(new java.awt.Color(235, 122, 102));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtStreetAddress.setForeground(new java.awt.Color(15, 19, 52));
        txtStreetAddress.setToolTipText("");
        txtStreetAddress.setBorderColor(new java.awt.Color(51, 51, 51));
        txtStreetAddress.setBotonColor(new java.awt.Color(235, 122, 102));
        txtStreetAddress.setPhColor(new java.awt.Color(235, 122, 102));
        txtStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressActionPerformed(evt);
            }
        });

        txtCity.setForeground(new java.awt.Color(15, 19, 52));
        txtCity.setToolTipText("");
        txtCity.setBorderColor(new java.awt.Color(51, 51, 51));
        txtCity.setBotonColor(new java.awt.Color(235, 122, 102));
        txtCity.setPhColor(new java.awt.Color(235, 122, 102));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtState.setForeground(new java.awt.Color(15, 19, 52));
        txtState.setToolTipText("");
        txtState.setBorderColor(new java.awt.Color(51, 51, 51));
        txtState.setBotonColor(new java.awt.Color(235, 122, 102));
        txtState.setPhColor(new java.awt.Color(235, 122, 102));
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        txtZipCode.setForeground(new java.awt.Color(15, 19, 52));
        txtZipCode.setToolTipText("");
        txtZipCode.setBorderColor(new java.awt.Color(51, 51, 51));
        txtZipCode.setBotonColor(new java.awt.Color(235, 122, 102));
        txtZipCode.setPhColor(new java.awt.Color(235, 122, 102));
        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        txtNumberPeopleAffected.setForeground(new java.awt.Color(15, 19, 52));
        txtNumberPeopleAffected.setToolTipText("");
        txtNumberPeopleAffected.setBorderColor(new java.awt.Color(51, 51, 51));
        txtNumberPeopleAffected.setBotonColor(new java.awt.Color(235, 122, 102));
        txtNumberPeopleAffected.setPhColor(new java.awt.Color(235, 122, 102));
        txtNumberPeopleAffected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberPeopleAffectedActionPerformed(evt);
            }
        });

        txtAffectedChildren.setForeground(new java.awt.Color(15, 19, 52));
        txtAffectedChildren.setToolTipText("");
        txtAffectedChildren.setBorderColor(new java.awt.Color(51, 51, 51));
        txtAffectedChildren.setBotonColor(new java.awt.Color(235, 122, 102));
        txtAffectedChildren.setPhColor(new java.awt.Color(235, 122, 102));
        txtAffectedChildren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAffectedChildrenActionPerformed(evt);
            }
        });

        txtAddectedElders.setForeground(new java.awt.Color(15, 19, 52));
        txtAddectedElders.setToolTipText("");
        txtAddectedElders.setBorderColor(new java.awt.Color(51, 51, 51));
        txtAddectedElders.setBotonColor(new java.awt.Color(235, 122, 102));
        txtAddectedElders.setPhColor(new java.awt.Color(235, 122, 102));
        txtAddectedElders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddectedEldersActionPerformed(evt);
            }
        });

        healthcampDate.setBackground(new java.awt.Color(255, 255, 255));
        healthcampDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBackground(new java.awt.Color(235, 122, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("CAMP REQUEST");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCampID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(healthcampDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumberPeopleAffected, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmboEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtAffectedChildren, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtAddectedElders, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAffectedChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddectedElders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCampID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumberPeopleAffected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(healthcampDate, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HealthcampRequestJPanel health = (HealthcampRequestJPanel) component;
        health.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bttnBackActionPerformed

    private void bttnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnApproveActionPerformed
        int check = 0;
        int checkdate = 0;
        Enterprise enterprise = null;

        if (healthcampDate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Event Date cannot be empty!");
        } else {
            check = 1;
            //System.out.println(business.getNetworkList());
            // enterprise = new CampEnterprise(Integer.toString(request.getCampId()));
            int campId1 = request.getCampId();
            String city1 = request.getCity();

            String noOfPeople1 = request.getPeopleAffected();
            String percentChild1 = request.getPercentChild();
            String percentElder1 = request.getPercentElder();
            String state1 = request.getState();
            String street1 = request.getStreet();
            String zipCode1 = request.getZipcode();
            String name1 = request.getCampId() + "_" + request.getZipcode();
            String enter = cmboEnterprise.getSelectedItem().toString();

//            Date eventDay = null;
            Date sysDate = null;
//            SimpleDateFormat format = new SimpleDateFormat("MM-dd-yyyy");
//            format.setLenient(false);

            try {

                //  eventDay = format.parse(eventDate.getDate());
                sysDate = new Date();
                long diff = sysDate.getTime() - healthcampDate.getDate().getTime();
                long diff1 = healthcampDate.getDate().getTime() - sysDate.getTime();
                long diff1Days = diff1 / (24 * 60 * 60 * 1000);
                long years = diff1Days / 365;

                if (diff > 0) {
                    JOptionPane.showMessageDialog(null, "Cannot enter a previous date");
                    checkdate = 1;
                }

                if (diff1Days >= 10 && check == 1 && checkdate == 0) {

                    enterprise = network.getEnterpriseDirectory().createAndAddCampEnterprise(name1, street1, city1, state1, zipCode1, noOfPeople1, percentChild1, percentElder1, campId1, healthcampDate.getDate(), Enterprise.EnterpriseType.Camp, enter);
                    Employee employee = enterprise.getEmployeeDirectory().createEmployee("admin");
                    String username = "admin_" + name1;
                    enterprise.getUserAccountDirectory().createUserAccount(username, "admin", employee, new AdminRole());
                    enterprise.getOrganizationDirectory().createOrganization(Organization.OrganizationType.VolunteerCamp);

                    JOptionPane.showMessageDialog(this, "Camp Request Approved. Volunteer can Enroll for the Health Camp now!");
                    healthcampDate.setEnabled(false);
                    cmboEnterprise.setEnabled(false);
                    bttnApprove.setEnabled(false);
                    request.setEventDate(healthcampDate.getDate());
//                    campID.setText("");
//                    fName.setText("");
//                    city.setText("");
//                    noOfPeople.setText("");
//                    percentChild.setText("");
//                    percentElder.setText("");
//                    state.setText("");
//                    street.setText("");
//                    zipCode.setText("");
//                    healthcampDate.setDate(null);

                    request.setStatus("Completed");
                    request.setHospital(cmboEnterprise.getSelectedItem().toString());
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter a Date after 10 days");
                }
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Please Enter Appropriate Date MM-dd-yyyy");

            }
            // enterpriseList.add(enterprise);
        }

    }//GEN-LAST:event_bttnApproveActionPerformed

    private void txtCampIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void txtNumberPeopleAffectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberPeopleAffectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberPeopleAffectedActionPerformed

    private void txtAffectedChildrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAffectedChildrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAffectedChildrenActionPerformed

    private void txtAddectedEldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddectedEldersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddectedEldersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle bttnApprove;
    private rojerusan.RSMaterialButtonRectangle bttnBack;
    private rojerusan.RSComboMetro cmboEnterprise;
    private com.toedter.calendar.JDateChooser healthcampDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSMetroTextPlaceHolder txtAddectedElders;
    private rojerusan.RSMetroTextPlaceHolder txtAffectedChildren;
    private rojerusan.RSMetroTextPlaceHolder txtCampID;
    private rojerusan.RSMetroTextPlaceHolder txtCity;
    private rojerusan.RSMetroTextPlaceHolder txtName;
    private rojerusan.RSMetroTextPlaceHolder txtNumberPeopleAffected;
    private rojerusan.RSMetroTextPlaceHolder txtState;
    private rojerusan.RSMetroTextPlaceHolder txtStreetAddress;
    private rojerusan.RSMetroTextPlaceHolder txtZipCode;
    // End of variables declaration//GEN-END:variables
}
